digits = []
zero = []
zero.append('                     ')
zero.append('                     ')
zero.append('                     ')
zero.append('        #####        ')
zero.append('      #### ####      ')
zero.append('     ##       ##     ')
zero.append('     ##  @@@  ##     ')
zero.append('    ##  @@@@@  ##    ')
zero.append('    ##  @@@@@  ##    ')
zero.append('    ##  @@@@@  ##    ')
zero.append('    ##  @@@@@  ##    ')
zero.append('    ##  @@@@@  ##    ')
zero.append('    ##  @@@@@  ##    ')
zero.append('    ##  @@@@@  ##    ')
zero.append('     ##  @@@  ##     ')
zero.append('     ##       ##     ')
zero.append('      #### ####      ')
zero.append('        #####        ')
zero.append('                     ')
zero.append('                     ')
zero.append('                     ')
digits.append(zero)

uno = []
uno.append('                     ')
uno.append('                     ')
uno.append('                     ')
uno.append('         ###         ')
uno.append('      ######         ')
uno.append('         ###         ')
uno.append('       @ ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('         ###         ')
uno.append('                     ')
uno.append('                     ')
uno.append('                     ')
digits.append(uno)

due = []
due.append('                     ')
due.append('                     ')
due.append('                     ')
due.append('       ########      ')
due.append('     ###      ##     ')
due.append('    ###   @    ##    ')
due.append('        @@@@    ##   ')
due.append('    @@@@@@@     ##   ')
due.append('    @@@        ##    ')
due.append('              ##     ')
due.append('             ##      ')
due.append('           ###       ')
due.append('          ##         ')
due.append('        ###          ')
due.append('      ###    @@      ')
due.append('    ###    @@@@      ')
due.append('   ##                ')
due.append('   ###############   ')
due.append('                     ')
due.append('                     ')
due.append('                     ')
digits.append(due)

tre = []
tre.append('                     ')
tre.append('                     ')
tre.append('                     ')
tre.append('        #####        ')
tre.append('     ###########     ')
tre.append('    ####     ####    ')
tre.append('          @    ###   ')
tre.append('         @@@   ###   ')
tre.append('             ####    ')
tre.append('            ####     ')
tre.append('          ####  @    ')
tre.append('            ####     ')
tre.append('             ####    ')
tre.append('         @@@   ###   ')
tre.append('          @    ###   ')
tre.append('    ####     ####    ')
tre.append('     ###########     ')
tre.append('        #####        ')
tre.append('                     ')
tre.append('                     ')
tre.append('                     ')
digits.append(tre)

quattro = []
quattro.append('                     ')
quattro.append('                     ')
quattro.append('                     ')
quattro.append('         ####        ')
quattro.append('        #####        ')
quattro.append('       ### ##        ')
quattro.append('      ###  ##        ')
quattro.append('     ###   ##        ')
quattro.append('    ###  @ ##        ')
quattro.append('   ###  @@ ## @      ')
quattro.append('   ###     ##        ')
quattro.append('   ###############   ')
quattro.append('   ###############   ')
quattro.append('           ##        ')
quattro.append('       @   ## @      ')
quattro.append('           ##        ')
quattro.append('           ##        ')
quattro.append('           ##        ')
quattro.append('                     ')
quattro.append('                     ')
quattro.append('                     ')
digits.append(quattro)

cinque = []
cinque.append('                     ')
cinque.append('                     ')
cinque.append('                     ')
cinque.append('   ###############   ')
cinque.append('   ###############   ')
cinque.append('   ###               ')
cinque.append('   ###   @@@@@@@@    ')
cinque.append('   ###               ')
cinque.append('   #############     ')
cinque.append('   ##############    ')
cinque.append('   ####       ###    ')
cinque.append('               ###   ')
cinque.append('   @@@@@@@     ###   ')
cinque.append('   @@@@@       ###   ')
cinque.append('              ###    ')
cinque.append('    ###     #####    ')
cinque.append('     ###########     ')
cinque.append('        #####        ')
cinque.append('                     ')
cinque.append('                     ')
cinque.append('                     ')
digits.append(cinque)

sei = []
sei.append('                     ')
sei.append('                     ')
sei.append('                     ')
sei.append('            ####     ')
sei.append('          ####       ')
sei.append('    @@  ####         ')
sei.append('    @  ####          ')
sei.append('      ####           ')
sei.append('     ####  @         ')
sei.append('    ####  @@         ')
sei.append('   ####              ')
sei.append('   ###########       ')
sei.append('   ##############    ')
sei.append('   ###         ###   ')
sei.append('    ##  @@@@@  ##    ')
sei.append('    ###   @   ###    ')
sei.append('     ####   ####     ')
sei.append('        #####        ')
sei.append('                     ')
sei.append('                     ')
sei.append('                     ')
digits.append(sei)

sette = []
sette.append('                     ')
sette.append('                     ')
sette.append('                     ')
sette.append('   ###############   ')
sette.append('   ###############   ')
sette.append('               ###   ')
sette.append('        @@@   ###    ')
sette.append('        @@   ###     ')
sette.append('            ###      ')
sette.append('           ###       ')
sette.append('          ###        ')
sette.append('         ##          ')
sette.append('        ##           ')
sette.append('        ##           ')
sette.append('        ##           ')
sette.append('       ##            ')
sette.append('       ##            ')
sette.append('       ##            ')
sette.append('                     ')
sette.append('                     ')
sette.append('                     ')
digits.append(sette)

otto = []
otto.append('                     ')
otto.append('                     ')
otto.append('                     ')
otto.append('        #####        ')
otto.append('       ##   ##       ')
otto.append('      ##  @  ##      ')
otto.append('      ##  @  ##      ')
otto.append('       ##   ##       ')
otto.append('       #######       ')
otto.append('      #########      ')
otto.append('     ###     ###     ')
otto.append('     ##  @@@  ##     ')
otto.append('     #  @@@@@  #     ')
otto.append('     #  @@@@@  #     ')
otto.append('     ##  @@@  ##     ')
otto.append('      ##     ##      ')
otto.append('      #### ####      ')
otto.append('        #####        ')
otto.append('                     ')
otto.append('                     ')
otto.append('                     ')
digits.append(otto)

nove = sei[::-1]
for i in range(len(nove)):
    nove[i] = nove[i][::-1]
digits.append(nove)

dash = ['   @@@@@@@@@@@@@@@   ' ,'      #########      ', '                     ']